var datos = [
    ["dark indigo", "2", "clear indigo"],
    ["mirrored gold", "2", "pale blue", "1", "dark violet"],
    ["dim aqua", "1", "mirrored beige"],
    ["dim fuchsia", "5", "dark red", "1", "muted green", "4", "clear indigo"],
    ["shiny fuchsia", "4", "wavy teal", "4", "dim cyan", "4", "light green", "1", "vibrant tomato"],
    ["posh chartreuse", "2", "faded blue", "2", "pale plum", "2", "posh coral", "4", "vibrant bronze"],
    ["striped red", "3", "vibrant red"],
    ["striped purple", "5", "shiny brown"],
    ["dark silver", "1", "dull aqua", "4", "dim magenta"],
    ["dark chartreuse", "2", "plaid black", "4", "light bronze", "5", "dotted cyan"],
    ["shiny turquoise", "1", "shiny brown"],
    ["shiny crimson", "no other"],
    ["clear purple", "4", "bright red"],
    ["dim white", "4", "posh violet", "2", "light orange"],
    ["plaid lime", "4", "muted silver", "2", "vibrant tan"],
    ["clear fuchsia", "3", "muted purple", "4", "striped coral"],
    ["dim plum", "4", "posh purple", "2", "faded tomato", "1", "mirrored magenta", "3", "dull lime"],
    ["dull white", "4", "light silver", "5", "drab purple", "2", "wavy orange", "1", "striped coral"],
    ["dull tomato", "3", "clear cyan", "5", "dark turquoise", "4", "light orange", "3", "vibrant red"],
    ["plaid tan", "5", "faded brown", "5", "bright bronze"],
    ["mirrored fuchsia", "5", "shiny brown", "3", "dim magenta"],
    ["wavy aqua", "2", "light beige", "3", "vibrant white", "2", "vibrant gold", "5", "shiny tomato"],
    ["clear white", "3", "dim maroon", "4", "vibrant brown", "1", "dim chartreuse"],
    ["muted yellow", "3", "shiny crimson", "4", "posh purple", "2", "dim plum", "3", "shiny tomato"],
    ["faded cyan", "5", "mirrored crimson"],
    ["posh violet", "3", "dim lavender", "3", "vibrant teal"],
    ["mirrored magenta", "1", "posh brown", "4", "shiny teal", "2", "shiny crimson"],
    ["mirrored purple", "2", "clear aqua"],
    ["wavy salmon", "1", "dull aqua", "1", "dark silver"],
    ["plaid purple", "2", "clear aqua", "5", "pale brown", "3", "bright chartreuse"],
    ["posh teal", "1", "pale turquoise", "3", "drab cyan"],
    ["pale tomato", "2", "dark beige"],
    ["muted plum", "5", "dotted gold", "5", "shiny plum", "4", "dull teal"],
    ["wavy red", "3", "clear turquoise", "4", "shiny chartreuse", "4", "dotted maroon"],
    ["wavy tomato", "4", "dark magenta", "1", "faded bronze"],
    ["shiny green", "3", "bright black", "2", "clear turquoise"],
    ["plaid turquoise", "4", "bright maroon"],
    ["vibrant silver", "5", "bright chartreuse", "2", "posh white", "3", "drab tomato"],
    ["posh olive", "3", "vibrant purple", "3", "shiny crimson", "5", "faded chartreuse"],
    ["clear bronze", "5", "dark magenta"],
    ["wavy teal", "1", "dim plum", "1", "pale aqua", "2", "posh purple", "2", "pale orange"],
    ["muted beige", "5", "dotted brown", "4", "mirrored green", "2", "plaid blue"],
    ["shiny maroon", "2", "pale green"],
    ["wavy purple", "5", "dark bronze"],
    ["vibrant cyan", "2", "drab blue", "5", "pale brown", "1", "mirrored magenta", "4", "pale orange"],
    ["wavy gray", "5", "pale crimson", "5", "light aqua", "4", "muted red"],
    ["clear tomato", "4", "dark coral"],
    ["shiny red", "4", "shiny tan", "4", "pale cyan"],
    ["muted brown", "5", "dull olive", "2", "pale silver", "5", "faded plum"],
    ["shiny violet", "4", "wavy teal"],
    ["posh white", "4", "light fuchsia", "1", "posh purple", "4", "posh green"],
    ["dim maroon", "5", "dim gold", "1", "clear black"],
    ["dull orange", "1", "clear teal", "3", "dull gray"],
    ["posh fuchsia", "1", "faded gold", "4", "light bronze"],
    ["dim bronze", "1", "bright fuchsia"],
    ["dull salmon", "5", "muted tomato", "3", "dull olive", "4", "dark brown"],
    ["posh yellow", "5", "dull indigo", "1", "dotted green", "3", "shiny chartreuse"],
    ["muted bronze", "4", "pale brown"],
    ["wavy plum", "4", "shiny teal", "4", "vibrant crimson"],
    ["dark maroon", "2", "clear maroon", "3", "light crimson"],
    ["posh gray", "2", "drab maroon", "3", "dotted aqua"],
    ["pale maroon", "2", "vibrant turquoise", "2", "wavy tan", "5", "clear orange", "2", "clear beige"],
    ["mirrored crimson", "3", "dark cyan", "3", "dark silver"],
    ["shiny bronze", "3", "drab tomato", "3", "vibrant tan"],
    ["pale teal", "4", "clear brown", "4", "vibrant gray", "3", "bright plum", "4", "dull olive"],
    ["plaid maroon", "1", "mirrored blue", "4", "bright chartreuse"],
    ["plaid blue", "4", "light lime"],
    ["dotted brown", "5", "shiny violet", "2", "shiny lavender", "1", "striped crimson"],
    ["pale purple", "2", "clear tomato", "5", "vibrant orange", "5", "dark green", "1", "vibrant silver"],
    ["clear lavender", "1", "wavy cyan", "5", "dotted crimson", "5", "dark bronze", "3", "light bronze"],
    ["light cyan", "5", "light lime", "1", "mirrored teal"],
    ["dull blue", "3", "clear lime", "1", "light turquoise", "1", "shiny gray"],
    ["faded gray", "2", "faded crimson", "1", "pale red", "3", "striped bronze"],
    ["drab maroon", "2", "bright coral"],
    ["plaid gold", "2", "shiny gold", "1", "wavy fuchsia", "2", "dull aqua", "4", "mirrored indigo"],
    ["mirrored orange", "3", "muted coral"],
    ["dull yellow", "1", "drab maroon", "4", "posh purple", "5", "plaid cyan", "4", "vibrant cyan"],
    ["plaid aqua", "2", "bright silver", "2", "posh blue", "3", "drab olive", "2", "mirrored fuchsia"],
    ["shiny olive", "3", "dim tan", "1", "dark gray", "4", "mirrored brown", "5", "mirrored magenta"],
    ["wavy bronze", "4", "mirrored gray", "1", "light lavender", "4", "dull yellow"],
    ["dotted orange", "1", "plaid teal", "5", "pale silver", "1", "drab bronze"],
    ["dull magenta", "1", "muted violet", "2", "muted black"],
    ["drab indigo", "3", "pale blue", "1", "muted aqua", "3", "bright fuchsia", "1", "striped white"],
    ["faded turquoise", "1", "pale lavender", "1", "shiny indigo"],
    ["shiny lavender", "2", "faded bronze", "3", "clear green", "5", "dim turquoise", "5", "striped olive"],
    ["faded yellow", "1", "faded chartreuse"],
    ["vibrant gray", "3", "clear gold", "1", "dotted coral", "4", "light lime", "2", "light lavender"],
    ["bright aqua", "2", "faded chartreuse"],
    ["bright yellow", "4", "dark blue"],
    ["mirrored tomato", "2", "posh blue"],
    ["shiny orange", "3", "striped black"],
    ["bright tan", "3", "dim gold"],
    ["light fuchsia", "4", "dotted bronze", "2", "posh purple"],
    ["striped coral", "2", "mirrored fuchsia", "4", "faded chartreuse", "3", "dull brown"],
    ["bright cyan", "3", "mirrored lime", "2", "posh purple", "3", "light plum", "3", "striped brown"],
    ["pale violet", "3", "wavy cyan"],
    ["bright lavender", "2", "shiny crimson", "1", "plaid magenta", "4", "dark turquoise"],
    ["wavy maroon", "4", "dull lavender", "2", "dim turquoise", "2", "light green", "1", "clear lime"],
    ["drab tomato", "1", "light crimson", "5", "faded gold", "5", "drab cyan"],
    ["dotted magenta", "1", "dotted beige"],
    ["clear green", "4", "posh purple"],
    ["shiny teal", "2", "pale turquoise"],
    ["clear salmon", "3", "clear aqua"],
    ["dark gold", "1", "pale tan"],
    ["mirrored gray", "1", "muted purple"],
    ["vibrant indigo", "3", "muted coral", "5", "shiny gray", "1", "dark yellow"],
    ["pale olive", "2", "posh white", "3", "dull white", "5", "light silver"],
    ["bright bronze", "3", "dull yellow"],
    ["dark yellow", "1", "bright black", "1", "clear teal"],
    ["dim cyan", "4", "wavy crimson", "4", "muted green"],
    ["shiny blue", "1", "pale beige", "1", "plaid magenta", "1", "dark magenta", "3", "dim tomato"],
    ["pale green", "5", "dotted crimson", "5", "posh purple", "4", "pale aqua", "2", "faded tomato"],
    ["faded coral", "1", "striped maroon", "5", "drab salmon", "5", "muted orange", "1", "dark blue"],
    ["light beige", "3", "light red", "1", "mirrored red", "3", "drab salmon", "2", "wavy teal"],
    ["wavy yellow", "2", "clear coral", "2", "pale turquoise"],
    ["dim lavender", "2", "dull silver", "3", "dull gray", "2", "wavy crimson"],
    ["dotted white", "1", "posh turquoise", "3", "faded gold", "1", "mirrored beige"],
    ["dotted red", "2", "plaid gray"],
    ["light black", "3", "faded chartreuse", "4", "dark yellow", "5", "plaid cyan"],
    ["vibrant black", "2", "faded fuchsia", "3", "vibrant bronze", "3", "dark brown", "5", "bright purple"],
    ["plaid olive", "2", "faded gray", "1", "wavy purple"],
    ["pale plum", "3", "pale tan", "1", "posh coral", "2", "dim fuchsia"],
    ["vibrant violet", "1", "clear coral"],
    ["mirrored indigo", "1", "faded violet"],
    ["posh lime", "3", "faded gray", "4", "dim indigo", "1", "wavy olive", "5", "bright violet"],
    ["pale bronze", "5", "plaid gold"],
    ["shiny purple", "3", "dark silver", "5", "dark aqua", "5", "mirrored indigo", "3", "plaid teal"],
    ["muted turquoise", "4", "clear teal"],
    ["light turquoise", "2", "muted coral", "2", "clear beige", "3", "clear maroon"],
    ["vibrant purple", "4", "dull aqua", "1", "light crimson"],
    ["dotted yellow", "2", "wavy yellow"],
    ["bright salmon", "5", "striped coral", "4", "dim red", "3", "faded tan"],
    ["drab tan", "2", "clear yellow"],
    ["plaid violet", "2", "pale plum", "3", "dim lavender", "5", "clear tan"],
    ["dull tan", "1", "dotted aqua"],
    ["dotted blue", "4", "vibrant maroon", "4", "drab tomato", "5", "light bronze", "1", "posh bronze"],
    ["light silver", "5", "vibrant purple"],
    ["muted blue", "4", "bright coral", "3", "faded blue", "5", "dull lime", "5", "pale brown"],
    ["dotted lime", "3", "light aqua", "4", "dull brown"],
    ["dotted aqua", "1", "mirrored fuchsia", "5", "wavy cyan", "3", "wavy tan"],
    ["faded lavender", "4", "shiny chartreuse", "4", "faded violet", "2", "striped tan"],
    ["bright violet", "1", "shiny gold", "5", "pale beige", "2", "pale orange", "3", "wavy crimson"],
    ["striped turquoise", "3", "drab blue"],
    ["dim black", "2", "muted coral", "2", "pale plum", "2", "shiny teal"],
    ["striped violet", "5", "mirrored white", "2", "striped coral"],
    ["pale gray", "4", "faded chartreuse", "2", "vibrant aqua"],
    ["drab cyan", "5", "bright fuchsia"],
    ["wavy olive", "3", "striped beige"],
    ["faded aqua", "4", "vibrant teal", "1", "dark olive", "1", "bright crimson", "1", "plaid indigo"],
    ["wavy blue", "4", "clear maroon", "4", "dim cyan", "2", "mirrored gray"],
    ["clear magenta", "3", "vibrant purple", "4", "dotted maroon", "1", "plaid green", "5", "drab green"],
    ["faded olive", "5", "striped turquoise"],
    ["vibrant olive", "2", "shiny teal", "4", "shiny maroon", "5", "clear tomato"],
    ["muted red", "3", "dim magenta", "1", "shiny teal"],
    ["bright indigo", "5", "muted red"],
    ["faded lime", "5", "posh maroon", "2", "pale indigo", "2", "posh turquoise", "5", "dim indigo"],
    ["plaid fuchsia", "2", "dim fuchsia", "3", "light aqua"],
    ["posh bronze", "4", "dull aqua"],
    ["striped green", "1", "dotted lime"],
    ["faded maroon", "3", "mirrored turquoise", "4", "dark orange"],
    ["dim turquoise", "2", "drab cyan", "2", "clear lime", "2", "dim salmon"],
    ["bright gold", "2", "mirrored blue", "2", "vibrant purple", "5", "drab purple"],
    ["light red", "1", "drab fuchsia", "3", "drab maroon", "5", "dim plum", "5", "pale red"],
    ["vibrant lime", "3", "dull chartreuse", "4", "pale crimson", "5", "dark orange", "3", "vibrant purple"],
    ["pale magenta", "2", "vibrant purple", "4", "wavy olive"],
    ["drab turquoise", "5", "dotted crimson"],
    ["posh beige", "5", "dark gray", "2", "striped maroon", "3", "muted red"],
    ["wavy gold", "2", "dull lavender", "1", "dotted red", "1", "drab tomato", "4", "dark gray"],
    ["clear tan", "5", "dull gray", "2", "wavy maroon", "2", "pale red"],
    ["wavy green", "5", "pale magenta", "2", "vibrant coral", "2", "bright turquoise"],
    ["mirrored lavender", "5", "dotted beige"],
    ["clear beige", "2", "muted purple"],
    ["clear gray", "5", "shiny green", "3", "plaid gold", "4", "vibrant indigo", "1", "pale brown"],
    ["mirrored lime", "1", "muted gray", "1", "striped red", "5", "plaid brown", "1", "plaid black"],
    ["clear olive", "1", "posh olive", "1", "striped bronze"],
    ["wavy lavender", "3", "mirrored green", "3", "bright coral"],
    ["muted green", "4", "pale orange"],
    ["posh black", "1", "wavy bronze", "2", "dim cyan"],
    ["posh purple", "no other"],
    ["wavy crimson", "3", "dim fuchsia", "5", "dull chartreuse", "1", "dark yellow"],
    ["bright lime", "2", "pale crimson", "2", "drab green", "3", "dull orange"],
    ["mirrored black", "5", "light beige", "1", "striped olive", "2", "plaid purple", "3", "vibrant tan"],
    ["dull turquoise", "5", "striped violet", "3", "striped lime", "4", "pale black", "3", "drab brown"],
    ["striped yellow", "2", "dark crimson", "1", "clear fuchsia"],
    ["drab orange", "3", "shiny blue", "2", "clear green", "2", "muted plum"],
    ["light coral", "3", "mirrored fuchsia", "1", "shiny tomato", "2", "dull aqua", "2", "muted yellow"],
    ["posh silver", "1", "light coral"],
    ["light tomato", "1", "faded silver"],
    ["dark turquoise", "3", "dull yellow", "4", "posh turquoise"],
    ["dotted olive", "2", "clear bronze"],
    ["faded beige", "5", "posh teal", "2", "drab beige", "3", "plaid lavender", "4", "drab purple"],
    ["drab lavender", "4", "faded gray", "2", "pale blue", "4", "faded gold", "3", "dark silver"],
    ["faded salmon", "5", "light lavender"],
    ["drab crimson", "3", "drab aqua", "4", "striped yellow", "2", "shiny fuchsia", "4", "dark olive"],
    ["clear brown", "1", "striped coral", "2", "shiny gold"],
    ["wavy black", "3", "dull orange", "3", "faded salmon", "2", "plaid white"],
    ["faded brown", "2", "plaid cyan", "5", "light lavender", "3", "bright coral", "2", "drab maroon"],
    ["vibrant yellow", "4", "striped bronze"],
    ["posh aqua", "4", "light crimson", "1", "dark red", "4", "bright lavender", "4", "striped beige"],
    ["pale cyan", "1", "dark olive", "2", "pale orange", "1", "vibrant white"],
    ["muted white", "1", "light brown"],
    ["bright fuchsia", "2", "posh brown", "5", "clear coral", "1", "dim plum"],
    ["mirrored aqua", "3", "light fuchsia", "3", "bright aqua", "2", "light aqua"],
    ["wavy coral", "2", "muted yellow", "3", "drab silver", "5", "dark silver"],
    ["muted fuchsia", "1", "plaid black", "5", "shiny yellow"],
    ["dim green", "4", "wavy aqua", "2", "light cyan", "1", "shiny gray"],
    ["drab black", "2", "dotted maroon", "5", "clear maroon", "3", "mirrored coral", "1", "dim salmon"],
    ["shiny coral", "4", "light plum", "4", "mirrored chartreuse", "3", "wavy white"],
    ["posh indigo", "2", "dark cyan", "5", "pale brown", "1", "dull blue", "3", "striped red"],
    ["pale brown", "4", "dull red", "4", "shiny teal", "4", "shiny crimson", "2", "bright fuchsia"],
    ["plaid coral", "1", "dim maroon", "4", "clear plum", "5", "dark green", "4", "shiny purple"],
    ["shiny gold", "1", "pale aqua", "3", "dark cyan", "5", "vibrant purple", "2", "drab blue"],
    ["plaid brown", "1", "wavy crimson"],
    ["muted teal", "2", "drab turquoise", "2", "clear tan", "4", "shiny violet", "1", "vibrant tan"],
    ["drab blue", "2", "bright fuchsia", "2", "clear coral"],
    ["light olive", "2", "faded purple", "4", "striped bronze"],
    ["drab yellow", "5", "shiny maroon", "4", "clear teal", "5", "wavy white"],
    ["clear blue", "5", "drab maroon", "2", "shiny gold", "3", "pale red", "3", "dotted gold"],
    ["wavy brown", "2", "pale beige", "5", "light yellow", "4", "striped aqua", "3", "wavy yellow"],
    ["dotted purple", "2", "dark teal", "5", "posh brown", "4", "plaid fuchsia", "2", "posh silver"],
    ["mirrored turquoise", "3", "dim tan"],
    ["dotted cyan", "3", "shiny lavender", "5", "clear aqua"],
    ["striped olive", "4", "dark cyan", "3", "dim plum"],
    ["faded fuchsia", "1", "shiny indigo", "2", "dull gold", "4", "mirrored salmon"],
    ["pale gold", "4", "clear gold", "3", "bright lime"],
    ["dull olive", "4", "striped chartreuse"],
    ["shiny tomato", "4", "shiny teal"],
    ["striped salmon", "5", "faded lavender", "1", "dim aqua"],
    ["pale salmon", "2", "dim orange"],
    ["dim salmon", "3", "posh purple", "5", "mirrored brown"],
    ["muted coral", "4", "light green", "3", "striped turquoise", "2", "plaid silver", "5", "vibrant maroon"],
    ["dull bronze", "2", "dim magenta", "1", "faded lavender"],
    ["drab gray", "1", "mirrored indigo", "1", "pale crimson", "3", "plaid teal"],
    ["muted chartreuse", "5", "light coral", "5", "vibrant turquoise", "3", "dark cyan", "5", "bright orange"],
    ["mirrored green", "2", "bright purple", "4", "posh bronze", "1", "shiny violet", "5", "clear teal"],
    ["bright orange", "1", "dull gray"],
    ["dim coral", "1", "posh salmon", "2", "striped salmon", "3", "striped chartreuse"],
    ["clear turquoise", "3", "wavy salmon", "1", "clear blue", "1", "drab tan"],
    ["bright teal", "1", "faded tan", "5", "striped teal", "3", "light lavender", "2", "dark olive"],
    ["shiny chartreuse", "2", "dull blue", "5", "drab turquoise", "4", "light aqua"],
    ["faded tan", "4", "drab purple"],
    ["plaid magenta", "5", "drab cyan", "4", "muted aqua"],
    ["muted purple", "no other"],
    ["vibrant green", "5", "striped crimson", "5", "clear beige", "3", "drab yellow"],
    ["vibrant salmon", "4", "clear red", "5", "wavy salmon"],
    ["vibrant tomato", "3", "light plum", "1", "posh white", "2", "wavy magenta"],
    ["wavy turquoise", "5", "dotted gold", "2", "light gray", "4", "drab tomato", "5", "wavy aqua"],
    ["dim olive", "3", "light magenta", "1", "dotted lime", "4", "dotted crimson", "3", "light salmon"],
    ["plaid lavender", "2", "dark turquoise", "5", "striped turquoise", "4", "wavy olive"],
    ["dark green", "3", "dotted gold"],
    ["faded purple", "5", "clear coral", "3", "mirrored green", "5", "drab coral", "3", "bright purple"],
    ["dotted crimson", "2", "wavy teal", "5", "light green", "5", "muted purple", "1", "plaid silver"],
    ["mirrored coral", "5", "striped turquoise", "1", "faded purple", "1", "shiny cyan"],
    ["mirrored cyan", "1", "mirrored chartreuse", "5", "wavy magenta"],
    ["shiny black", "2", "drab magenta", "2", "plaid bronze"],
    ["dark teal", "3", "dark white", "1", "muted chartreuse", "3", "dotted salmon", "4", "posh aqua"],
    ["dull teal", "2", "bright chartreuse", "3", "light black"],
    ["mirrored red", "2", "dotted crimson", "2", "drab cyan"],
    ["striped brown", "2", "pale red", "5", "light gray"],
    ["posh magenta", "4", "posh green", "4", "dotted bronze", "5", "dim tan"],
    ["pale lime", "5", "shiny blue"],
    ["plaid indigo", "3", "shiny maroon", "1", "dark yellow", "4", "dull gold"],
    ["light green", "2", "dull brown", "5", "bright coral"],
    ["muted olive", "3", "dotted bronze", "1", "shiny coral", "3", "dotted aqua", "2", "faded blue"],
    ["striped lime", "2", "faded salmon", "2", "pale white", "1", "plaid salmon", "1", "dark coral"],
    ["clear red", "3", "dark orange", "5", "faded magenta", "4", "dark lime"],
    ["faded bronze", "4", "light lavender"],
    ["dotted plum", "1", "faded tan", "3", "pale aqua", "2", "dull gray", "4", "plaid purple"],
    ["plaid salmon", "5", "light lime", "1", "posh bronze", "5", "wavy magenta", "1", "dark green"],
    ["dull plum", "4", "mirrored purple"],
    ["light indigo", "3", "dark silver", "1", "bright lime"],
    ["pale red", "5", "posh purple"],
    ["wavy chartreuse", "1", "light coral"],
    ["dull lavender", "5", "plaid purple", "4", "faded orange"],
    ["vibrant orange", "2", "drab violet"],
    ["light gold", "3", "plaid salmon"],
    ["faded teal", "1", "dotted maroon"],
    ["light chartreuse", "3", "dotted yellow", "1", "clear yellow", "3", "shiny teal", "4", "plaid lime"],
    ["faded white", "5", "drab turquoise", "1", "dark violet"],
    ["light lavender", "1", "vibrant magenta", "1", "pale brown"],
    ["light crimson", "5", "dull red"],
    ["mirrored silver", "2", "bright turquoise"],
    ["faded green", "5", "dark lime", "5", "dim crimson", "4", "dark silver", "1", "dotted white"],
    ["vibrant chartreuse", "5", "wavy gray", "5", "bright silver", "1", "dull indigo"],
    ["clear chartreuse", "5", "light brown", "2", "dim violet", "4", "faded orange"],
    ["dotted violet", "4", "dark white", "1", "muted brown", "4", "faded cyan", "5", "striped gray"],
    ["dotted green", "5", "bright silver", "4", "drab lime"],
    ["light bronze", "3", "dotted gold"],
    ["vibrant tan", "2", "dull chartreuse", "5", "clear gold", "1", "bright orange", "2", "dotted gold"],
    ["faded gold", "4", "shiny gold", "1", "dark red", "2", "dotted bronze", "1", "muted red"],
    ["plaid green", "4", "light gray", "1", "striped bronze"],
    ["clear yellow", "4", "drab blue"],
    ["mirrored yellow", "3", "vibrant tan", "2", "light crimson", "1", "light lime", "5", "bright teal"],
    ["dotted beige", "2", "pale beige", "3", "light lime", "3", "drab cyan", "3", "plaid green"],
    ["pale chartreuse", "1", "striped brown", "2", "faded gold"],
    ["wavy white", "4", "dotted gold", "5", "striped turquoise", "1", "mirrored chartreuse"],
    ["muted tomato", "5", "dark magenta"],
    ["dark lavender", "4", "pale indigo", "5", "shiny cyan"],
    ["pale black", "3", "clear tomato", "3", "vibrant gray"],
    ["dim orange", "5", "dark olive", "1", "vibrant silver", "3", "plaid brown", "1", "dull red"],
    ["bright plum", "5", "striped tomato", "2", "dotted beige"],
    ["posh tomato", "5", "faded tomato"],
    ["vibrant maroon", "5", "dark orange"],
    ["dim tan", "5", "muted yellow"],
    ["dotted tan", "4", "dark lime"],
    ["plaid red", "2", "posh beige", "3", "wavy tan", "1", "muted silver"],
    ["faded black", "1", "clear lavender", "4", "dotted lime", "3", "mirrored crimson", "2", "faded gray"],
    ["mirrored tan", "2", "vibrant white", "5", "mirrored beige", "4", "wavy turquoise", "4", "striped green"],
    ["dull violet", "5", "bright teal"],
    ["striped maroon", "2", "dull brown"],
    ["dull green", "4", "dim yellow", "3", "mirrored silver", "5", "muted chartreuse"],
    ["dull gray", "3", "vibrant purple", "3", "striped turquoise", "5", "wavy cyan"],
    ["posh salmon", "4", "light green", "4", "dull blue"],
    ["dark tan", "5", "muted bronze", "5", "clear lime", "5", "vibrant gray"],
    ["dark purple", "1", "clear cyan", "3", "vibrant tan", "5", "light magenta", "1", "dark blue"],
    ["plaid teal", "1", "wavy purple", "4", "mirrored crimson"],
    ["posh brown", "no other"],
    ["pale orange", "no other"],
    ["posh plum", "3", "light bronze", "3", "bright coral", "3", "shiny yellow", "3", "dark yellow"],
    ["bright olive", "2", "light silver"],
    ["posh red", "4", "dark turquoise", "1", "plaid cyan", "3", "dotted aqua"],
    ["muted violet", "3", "pale green", "5", "dull red"],
    ["plaid crimson", "3", "clear silver"],
    ["dotted gray", "1", "muted white"],
    ["dull brown", "1", "dull aqua", "4", "bright coral", "5", "shiny violet", "1", "light coral"],
    ["pale silver", "3", "mirrored brown", "2", "dark brown", "2", "vibrant indigo"],
    ["vibrant coral", "2", "pale red", "3", "bright teal", "5", "striped bronze", "1", "bright silver"],
    ["dark brown", "1", "pale brown", "1", "drab beige", "4", "mirrored chartreuse", "1", "clear teal"],
    ["dotted turquoise", "4", "wavy chartreuse", "2", "faded violet"],
    ["bright silver", "3", "dark silver", "5", "clear aqua", "1", "striped coral", "4", "vibrant violet"],
    ["plaid chartreuse", "3", "pale red", "4", "wavy teal", "3", "dark tomato"],
    ["bright red", "4", "pale red"],
    ["pale beige", "3", "posh purple", "2", "striped gold"],
    ["vibrant plum", "3", "posh green", "5", "plaid cyan", "4", "light silver"],
    ["bright white", "3", "dull gold", "5", "striped turquoise", "2", "bright tan"],
    ["dark magenta", "1", "pale aqua", "5", "faded bronze", "3", "dark orange", "3", "dim magenta"],
    ["bright beige", "4", "clear white", "2", "dotted plum", "2", "light brown", "1", "plaid gray"],
    ["bright black", "2", "pale turquoise", "5", "mirrored brown", "1", "mirrored magenta", "4", "dull lime"],
    ["bright gray", "3", "mirrored red", "5", "clear brown", "4", "muted violet"],
    ["muted magenta", "1", "posh bronze", "5", "mirrored brown", "1", "clear crimson", "1", "light lavender"],
    ["light teal", "4", "shiny tan"],
    ["dark gray", "4", "dotted bronze", "2", "pale red", "3", "pale brown", "5", "dim magenta"],
    ["muted black", "5", "light beige", "1", "dark tomato", "3", "striped coral", "3", "vibrant maroon"],
    ["dark red", "5", "muted red", "3", "dull lime", "2", "shiny tomato", "2", "pale brown"],
    ["bright brown", "4", "bright teal", "3", "plaid green"],
    ["plaid yellow", "4", "plaid bronze"],
    ["dark cyan", "2", "dim plum", "4", "shiny brown"],
    ["faded blue", "4", "faded yellow"],
    ["dull maroon", "3", "mirrored purple", "2", "faded silver", "5", "pale silver"],
    ["posh coral", "5", "dim gold"],
    ["faded chartreuse", "2", "clear coral", "5", "dim gold"],
    ["striped silver", "4", "faded cyan", "5", "wavy brown", "5", "bright tan", "3", "drab chartreuse"],
    ["plaid gray", "4", "faded tomato", "4", "dim cyan", "4", "dotted maroon", "5", "clear indigo"],
    ["plaid white", "4", "dim magenta", "4", "pale red"],
    ["dark black", "1", "drab tan", "4", "striped indigo"],
    ["vibrant white", "1", "dull aqua", "3", "dull red"],
    ["muted maroon", "3", "dim violet", "3", "faded orange", "1", "bright purple", "2", "dull cyan"],
    ["pale indigo", "3", "faded plum", "3", "clear tomato"],
    ["clear teal", "1", "light coral", "5", "faded bronze", "5", "faded chartreuse", "2", "striped olive"],
    ["muted tan", "3", "bright cyan"],
    ["light magenta", "5", "dark magenta", "3", "striped brown"],
    ["dark aqua", "3", "posh turquoise", "4", "pale fuchsia", "2", "bright orange", "4", "dim cyan"],
    ["bright tomato", "5", "wavy bronze", "4", "clear magenta", "4", "shiny fuchsia"],
    ["dark salmon", "4", "pale indigo", "4", "wavy magenta"],
    ["dim blue", "4", "pale magenta", "2", "muted tomato"],
    ["dark blue", "4", "shiny tomato"],
    ["drab aqua", "5", "clear cyan", "1", "dotted orange"],
    ["plaid tomato", "2", "clear red", "2", "dark tomato", "2", "bright gold"],
    ["vibrant crimson", "3", "dull blue"],
    ["light yellow", "2", "striped black", "2", "shiny brown", "5", "clear black"],
    ["pale white", "1", "posh plum"],
    ["dull gold", "5", "wavy crimson", "5", "pale aqua", "5", "mirrored cyan", "2", "drab tomato"],
    ["striped gray", "5", "shiny tomato", "3", "mirrored brown", "1", "posh brown"],
    ["drab salmon", "5", "vibrant yellow"],
    ["light purple", "1", "shiny turquoise"],
    ["striped lavender", "4", "mirrored gold", "3", "vibrant brown", "3", "wavy bronze", "2", "pale black"],
    ["vibrant beige", "2", "light yellow"],
    ["striped magenta", "4", "light black"],
    ["clear aqua", "2", "dark cyan", "1", "faded orange", "3", "mirrored gray", "2", "dark tomato"],
    ["dim teal", "2", "dark gray"],
    ["striped tomato", "4", "dark coral", "1", "faded blue"],
    ["striped gold", "4", "bright coral", "1", "shiny teal", "4", "dark silver"],
    ["light maroon", "4", "dotted coral"],
    ["pale blue", "2", "striped coral", "1", "vibrant white", "3", "drab maroon"],
    ["clear crimson", "3", "plaid chartreuse", "1", "pale bronze"],
    ["dim beige", "5", "drab tan"],
    ["pale turquoise", "no other"],
    ["dotted salmon", "2", "clear magenta", "4", "pale silver"],
    ["posh orange", "3", "dull aqua", "3", "vibrant gray", "4", "dull olive", "1", "mirrored magenta"],
    ["dark tomato", "3", "shiny lavender", "2", "drab beige", "3", "dark cyan"],
    ["shiny aqua", "3", "light maroon", "4", "muted turquoise", "2", "vibrant magenta"],
    ["bright purple", "3", "light silver", "3", "mirrored magenta"],
    ["shiny lime", "3", "dark olive", "1", "striped chartreuse", "1", "muted green"],
    ["bright crimson", "2", "muted indigo"],
    ["clear silver", "3", "mirrored red"],
    ["bright coral", "1", "dim gold", "2", "clear green", "3", "dark cyan"],
    ["pale crimson", "4", "shiny teal", "5", "drab maroon", "1", "pale brown"],
    ["wavy silver", "2", "dotted cyan", "1", "vibrant silver", "2", "light turquoise", "3", "light salmon"],
    ["muted salmon", "1", "shiny bronze", "5", "faded salmon", "4", "muted black", "1", "muted coral"],
    ["drab teal", "2", "vibrant violet", "4", "vibrant orange"],
    ["mirrored blue", "3", "mirrored fuchsia"],
    ["mirrored white", "4", "striped brown", "5", "mirrored cyan"],
    ["dull coral", "2", "bright magenta", "5", "clear tan"],
    ["dull aqua", "3", "dim magenta", "2", "light lavender"],
    ["faded crimson", "4", "striped maroon", "4", "dull lime", "5", "vibrant magenta"],
    ["light blue", "1", "plaid gold", "5", "plaid white", "1", "plaid black"],
    ["pale tan", "3", "posh green", "1", "dim fuchsia", "5", "vibrant yellow"],
    ["vibrant blue", "4", "pale gold", "1", "clear magenta"],
    ["vibrant red", "1", "plaid cyan", "2", "dim tan", "1", "muted red"],
    ["striped cyan", "5", "plaid blue", "3", "faded lavender"],
    ["dull silver", "2", "dark bronze", "5", "pale orange"],
    ["striped bronze", "1", "shiny tomato", "4", "muted yellow", "4", "striped turquoise"],
    ["light aqua", "5", "shiny violet"],
    ["drab white", "5", "faded gold", "1", "striped tomato", "1", "plaid salmon"],
    ["clear lime", "4", "mirrored brown", "2", "light lavender", "1", "light coral"],
    ["shiny tan", "4", "bright fuchsia", "1", "dark orange", "1", "dull lime"],
    ["bright turquoise", "1", "dim salmon", "3", "light green", "3", "shiny crimson", "2", "wavy cyan"],
    ["posh lavender", "1", "bright bronze", "2", "dull lavender", "1", "vibrant purple", "5", "shiny violet"],
    ["wavy indigo", "2", "striped violet", "1", "mirrored red", "1", "muted turquoise"],
    ["dull cyan", "5", "vibrant yellow", "2", "wavy salmon", "2", "striped olive", "5", "vibrant turquoise"],
    ["posh maroon", "2", "clear bronze", "3", "vibrant tan"],
    ["faded violet", "4", "shiny olive", "3", "posh magenta"],
    ["striped blue", "4", "dull tomato", "3", "bright plum"],
    ["mirrored teal", "4", "dark crimson", "5", "dotted coral", "2", "clear indigo", "5", "faded salmon"],
    ["bright magenta", "4", "clear turquoise", "5", "dim turquoise"],
    ["vibrant magenta", "5", "mirrored magenta", "2", "clear green"],
    ["clear cyan", "4", "pale turquoise", "3", "wavy maroon"],
    ["striped beige", "5", "mirrored magenta", "4", "clear fuchsia"],
    ["light white", "4", "pale brown", "3", "vibrant plum"],
    ["shiny silver", "5", "striped gray", "3", "drab silver", "3", "shiny beige", "4", "wavy salmon"],
    ["drab magenta", "5", "dark brown", "4", "shiny fuchsia"],
    ["dark white", "5", "posh fuchsia", "4", "shiny turquoise", "1", "vibrant cyan"],
    ["dim red", "1", "bright tan"],
    ["posh crimson", "5", "bright gray"],
    ["plaid silver", "4", "muted purple", "5", "faded gold"],
    ["dull indigo", "5", "dim violet", "5", "light maroon"],
    ["dotted fuchsia", "4", "pale yellow", "5", "dim gold", "2", "bright fuchsia"],
    ["light lime", "4", "striped aqua", "4", "shiny tan", "2", "striped bronze", "4", "dotted lime"],
    ["dark crimson", "2", "dim turquoise"],
    ["plaid bronze", "3", "posh red", "4", "mirrored silver", "2", "drab tan"],
    ["dark plum", "1", "pale coral", "4", "clear cyan", "5", "dim turquoise", "4", "striped crimson"],
    ["mirrored maroon", "5", "clear chartreuse", "2", "pale purple", "5", "clear fuchsia"],
    ["drab fuchsia", "2", "shiny olive", "5", "wavy salmon", "5", "drab lime"],
    ["bright chartreuse", "5", "bright turquoise", "3", "bright fuchsia"],
    ["dim indigo", "4", "wavy chartreuse", "3", "light coral", "1", "clear fuchsia", "2", "faded violet"],
    ["vibrant brown", "4", "mirrored silver", "4", "bright bronze", "3", "plaid purple"],
    ["striped black", "3", "shiny fuchsia"],
    ["wavy orange", "3", "clear maroon", "5", "drab magenta"],
    ["striped indigo", "4", "striped teal", "5", "dull lavender", "1", "muted red", "3", "wavy blue"],
    ["dark bronze", "3", "clear beige", "4", "drab cyan"],
    ["striped crimson", "1", "plaid cyan"],
    ["light salmon", "5", "pale yellow", "2", "plaid purple", "4", "dark indigo", "3", "striped white"],
    ["dotted indigo", "3", "mirrored magenta", "5", "striped gold", "3", "clear coral", "2", "wavy olive"],
    ["muted gold", "3", "wavy violet", "1", "wavy purple", "2", "dim gold"],
    ["clear orange", "1", "striped turquoise", "3", "posh turquoise", "3", "light plum", "3", "pale crimson"],
    ["faded magenta", "1", "drab blue", "2", "plaid green"],
    ["dark orange", "4", "drab tomato", "4", "mirrored brown", "1", "mirrored fuchsia", "1", "dim magenta"],
    ["pale fuchsia", "1", "clear lime"],
    ["dotted teal", "1", "dull fuchsia"],
    ["drab silver", "4", "pale red", "4", "clear chartreuse"],
    ["clear gold", "4", "pale crimson"],
    ["dotted bronze", "4", "mirrored brown", "2", "dull red", "1", "shiny tomato"],
    ["shiny brown", "no other"],
    ["pale yellow", "2", "mirrored brown", "5", "clear fuchsia"],
    ["dull chartreuse", "4", "posh magenta", "3", "mirrored magenta"],
    ["dim silver", "3", "faded coral"],
    ["dull purple", "1", "light blue", "5", "dark fuchsia", "5", "faded lavender", "3", "posh maroon"],
    ["light violet", "5", "dim olive"],
    ["wavy fuchsia", "1", "shiny olive", "4", "drab cyan"],
    ["muted aqua", "1", "shiny teal", "1", "dull lime", "5", "faded tomato", "5", "bright fuchsia"],
    ["striped orange", "5", "mirrored beige"],
    ["faded orange", "2", "wavy yellow", "2", "bright fuchsia", "3", "posh purple"],
    ["dotted lavender", "5", "dark blue", "3", "faded black", "4", "bright indigo"],
    ["wavy tan", "3", "plaid chartreuse", "1", "clear gold"],
    ["clear indigo", "4", "striped olive", "3", "mirrored brown"],
    ["light plum", "3", "mirrored indigo"],
    ["striped tan", "2", "vibrant cyan", "4", "dull lime", "2", "dim indigo"],
    ["plaid cyan", "1", "dim turquoise", "5", "clear lime", "1", "muted yellow", "3", "shiny brown"],
    ["drab gold", "1", "pale red", "4", "shiny purple"],
    ["drab violet", "5", "vibrant lime", "3", "vibrant aqua"],
    ["dim gold", "5", "dull lime", "3", "bright fuchsia", "1", "muted yellow"],
    ["muted cyan", "1", "mirrored black", "2", "clear orange", "5", "light crimson", "2", "mirrored teal"],
    ["dotted tomato", "1", "dotted bronze", "1", "dark orange", "4", "vibrant maroon", "5", "drab tomato"],
    ["striped chartreuse", "4", "mirrored fuchsia", "5", "dim magenta"],
    ["muted silver", "1", "vibrant turquoise", "1", "clear teal", "3", "bright black"],
    ["dim purple", "2", "light gray", "2", "dull aqua", "1", "pale turquoise", "3", "dim gold"],
    ["drab red", "4", "drab magenta"],
    ["muted indigo", "4", "light plum", "1", "striped beige"],
    ["dark olive", "4", "striped gold"],
    ["clear violet", "5", "vibrant white", "1", "wavy bronze", "3", "light plum", "1", "dark yellow"],
    ["striped aqua", "3", "dim salmon", "3", "light aqua"],
    ["bright maroon", "4", "shiny fuchsia", "5", "faded tomato", "1", "clear white", "4", "wavy yellow"],
    ["dark beige", "4", "faded blue", "4", "vibrant bronze", "2", "dark magenta"],
    ["posh turquoise", "4", "pale red", "3", "mirrored brown", "3", "mirrored indigo", "3", "striped gold"],
    ["drab purple", "5", "light green", "1", "shiny gold", "2", "striped turquoise", "5", "mirrored beige"],
    ["bright blue", "5", "dim indigo", "2", "dotted crimson", "1", "bright aqua", "5", "clear silver"],
    ["posh blue", "2", "shiny maroon", "3", "striped bronze"],
    ["wavy beige", "1", "dotted white", "3", "striped aqua", "3", "drab yellow"],
    ["dotted chartreuse", "5", "dotted bronze"],
    ["shiny gray", "2", "dim magenta"],
    ["mirrored beige", "3", "clear coral", "3", "dim salmon"],
    ["faded tomato", "2", "bright black", "5", "shiny tomato", "3", "mirrored brown", "5", "dull lime"],
    ["drab brown", "5", "clear black"],
    ["clear black", "4", "faded blue", "4", "posh turquoise", "4", "pale green", "4", "faded crimson"],
    ["vibrant aqua", "2", "faded bronze", "3", "dull aqua", "1", "clear beige", "2", "light lavender"],
    ["drab green", "3", "drab blue", "2", "pale red", "2", "posh green"],
    ["wavy cyan", "4", "faded blue", "2", "faded chartreuse", "2", "pale crimson"],
    ["plaid orange", "1", "muted yellow", "5", "dull chartreuse", "5", "dull gray", "3", "pale crimson"],
    ["dark lime", "4", "clear brown", "1", "drab fuchsia", "1", "light aqua", "4", "wavy tan"],
    ["dark violet", "3", "vibrant lime", "3", "clear fuchsia"],
    ["plaid beige", "2", "dark teal", "2", "posh indigo", "4", "mirrored red", "3", "vibrant gold"],
    ["striped fuchsia", "1", "dim tan", "4", "dotted plum", "5", "plaid olive"],
    ["pale aqua", "4", "shiny tomato", "3", "bright black"],
    ["shiny magenta", "5", "plaid blue", "2", "pale maroon", "2", "dim lavender"],
    ["dotted black", "2", "shiny aqua", "2", "dim crimson", "2", "plaid red", "5", "bright black"],
    ["clear coral", "no other"],
    ["shiny yellow", "2", "clear silver", "1", "vibrant cyan", "3", "striped crimson", "5", "light aqua"],
    ["dull beige", "3", "light green"],
    ["drab beige", "4", "bright black", "4", "light silver", "4", "light lavender"],
    ["shiny salmon", "2", "light blue", "1", "pale yellow"],
    ["pale lavender", "2", "shiny maroon", "5", "posh tan"],
    ["muted crimson", "1", "clear aqua", "2", "posh turquoise"],
    ["dim gray", "4", "pale tomato", "2", "dark chartreuse", "4", "clear red"],
    ["faded silver", "2", "drab beige", "3", "faded tomato", "4", "dull gold", "2", "mirrored magenta"],
    ["light gray", "5", "dark yellow"],
    ["dotted gold", "1", "light plum", "2", "faded tomato"],
    ["drab chartreuse", "4", "vibrant indigo"],
    ["dim tomato", "5", "clear gold", "4", "light gray", "4", "shiny green", "5", "faded yellow"],
    ["dull fuchsia", "3", "vibrant cyan", "1", "dim plum", "5", "posh bronze", "1", "shiny crimson"],
    ["shiny cyan", "5", "striped red", "5", "dim plum", "2", "striped turquoise"],
    ["dim yellow", "1", "dull chartreuse"],
    ["wavy magenta", "2", "dull lime", "2", "mirrored chartreuse", "2", "faded bronze"],
    ["posh tan", "5", "shiny tomato", "5", "drab maroon", "5", "vibrant maroon"],
    ["vibrant gold", "1", "dark orange", "2", "mirrored cyan", "1", "vibrant cyan", "2", "posh coral"],
    ["vibrant fuchsia", "2", "vibrant violet"],
    ["muted orange", "3", "striped gold", "1", "posh green", "3", "vibrant purple"],
    ["mirrored violet", "4", "clear chartreuse", "4", "dotted yellow", "2", "faded orange"],
    ["drab lime", "1", "mirrored magenta", "1", "striped turquoise"],
    ["dotted silver", "2", "dark cyan", "5", "drab olive"],
    ["dull crimson", "3", "clear yellow", "3", "vibrant cyan", "1", "bright turquoise"],
    ["light brown", "4", "shiny brown", "1", "plaid fuchsia"],
    ["vibrant teal", "2", "mirrored aqua", "5", "plaid silver"],
    ["vibrant turquoise", "2", "clear beige"],
    ["vibrant lavender", "2", "shiny teal", "5", "shiny blue", "2", "dull gray", "1", "muted crimson"],
    ["bright green", "1", "dull silver", "1", "dull red", "4", "vibrant indigo", "2", "clear coral"],
    ["mirrored bronze", "5", "dotted lavender", "2", "muted tomato", "4", "pale fuchsia", "4", "dim black"],
    ["mirrored chartreuse", "4", "dark gray", "3", "bright coral"],
    ["dull black", "2", "dim turquoise", "4", "drab maroon", "4", "shiny crimson"],
    ["shiny white", "4", "drab chartreuse", "4", "plaid salmon", "1", "dim green", "2", "muted orange"],
    ["dim chartreuse", "3", "dim bronze", "5", "posh lavender", "4", "drab bronze"],
    ["mirrored olive", "5", "striped brown", "4", "dim indigo"],
    ["muted lavender", "3", "dull teal", "4", "mirrored lime"],
    ["striped teal", "3", "shiny coral"],
    ["shiny indigo", "1", "dark bronze", "2", "light lavender", "4", "faded violet", "4", "drab green"],
    ["dim brown", "5", "dull aqua", "2", "plaid indigo"],
    ["light tan", "1", "muted yellow"],
    ["dim violet", "2", "dim magenta", "5", "shiny olive", "1", "wavy fuchsia", "5", "dull aqua"],
    ["dim crimson", "2", "faded bronze"],
    ["dull lime", "no other"],
    ["plaid black", "2", "clear beige", "5", "faded tomato", "1", "muted red"],
    ["clear maroon", "3", "muted coral"],
    ["faded red", "2", "posh purple", "4", "plaid gold", "1", "bright violet", "3", "shiny coral"],
    ["dotted coral", "4", "pale tan"],
    ["dull red", "3", "shiny teal"],
    ["mirrored brown", "no other"],
    ["drab olive", "2", "light fuchsia", "1", "dark brown", "2", "shiny olive"],
    ["shiny plum", "3", "striped olive", "1", "mirrored brown", "5", "faded blue", "4", "dark bronze"],
    ["plaid plum", "3", "shiny orange", "5", "dim magenta", "2", "bright crimson"],
    ["drab bronze", "4", "posh brown", "3", "dotted maroon"],
    ["striped white", "1", "bright lime"],
    ["drab coral", "1", "mirrored beige", "4", "plaid green", "2", "drab turquoise", "1", "drab bronze"],
    ["vibrant bronze", "1", "muted aqua", "3", "posh brown", "5", "light crimson"],
    ["dotted maroon", "2", "shiny tomato", "5", "dark cyan"],
    ["striped plum", "4", "dark fuchsia", "4", "dotted indigo"],
    ["faded indigo", "4", "dim orange", "2", "vibrant crimson", "3", "bright silver"],
    ["dim magenta", "1", "pale red", "1", "faded tomato", "3", "muted aqua"],
    ["muted lime", "1", "wavy magenta"],
    ["drab plum", "1", "striped green"],
    ["mirrored plum", "1", "bright gray", "4", "shiny tomato", "1", "mirrored salmon", "3", "shiny black"],
    ["dim lime", "3", "wavy orange", "1", "dark orange", "5", "vibrant indigo"],
    ["faded plum", "2", "shiny yellow", "5", "dark red", "1", "plaid bronze"],
    ["shiny beige", "2", "striped beige"],
    ["clear plum", "5", "vibrant violet", "2", "vibrant silver", "5", "dark magenta", "4", "posh lime"],
    ["pale coral", "1", "dotted lime", "3", "vibrant bronze"],
    ["dark fuchsia", "2", "striped turquoise", "2", "muted gray", "5", "dotted turquoise", "2", "dim black"],
    ["wavy violet", "5", "clear fuchsia", "4", "shiny fuchsia"],
    ["wavy lime", "4", "plaid yellow", "1", "striped bronze", "3", "shiny cyan", "5", "vibrant teal"],
    ["dark coral", "5", "drab lime", "1", "light brown", "3", "pale blue"],
    ["posh cyan", "3", "pale crimson", "5", "wavy gray", "5", "mirrored silver", "3", "wavy violet"],
    ["posh gold", "4", "plaid indigo", "2", "mirrored fuchsia", "1", "striped gold"],
    ["light orange", "4", "light coral", "4", "shiny indigo"],
    ["mirrored salmon", "5", "vibrant violet", "1", "drab purple", "5", "dark cyan"],
    ["posh green", "1", "light crimson", "3", "vibrant cyan", "2", "shiny brown", "2", "vibrant magenta"],
];

var bolsas = ["shiny gold"];
var cont = 0;
// console.log(datos[0]);
// console.log(datos[0][0]);
// console.log(datos[0][0][0]);


for (let k = 0; k < bolsas.length; k++) {

    for (let i = 0; i < datos.length; i++) {
        // console.log(datos[i]);
        for (let j = 1; j < datos[i].length; j++) {


            if (datos[i][j] == bolsas[k]) {
                // console.log(datos[i]);
                // bolsas.push(datos[i][0]);
                cont = 0;
                for (let p = 0; p < bolsas.length; p++) {
                    if (bolsas[p] == datos[i][0]) {
                        cont = cont + 1;
                    }
                }
                if (cont == 0) {
                    console.log(datos[i]);
                    bolsas.push(datos[i][0]);
                }

            }
        }
    }

}

console.log(bolsas);
console.log("cantidad de bolsas: ", bolsas.length - 1);


// light red bags contain 1 bright white bag, 2 muted yellow bags.